package platform

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"devhelper/internal/app"
)

func forCompose(cfg app.Config, p string) string {
	if runtime.GOOS == "windows" {
		return WSLToHost(cfg, p)
	}
	return p
}

// WriteEnv writes a .env file next to docker-compose.yml so `docker compose` can resolve paths and passwords.
func WriteEnv(cfg app.Config) error {
	if cfg.ComposeDir == "" {
		return fmt.Errorf("compose_dir is empty")
	}
	envPath := filepath.Join(cfg.ComposeDir, ".env")

	content := strings.Join([]string{
		"# generated by devhelper init",
		fmt.Sprintf("APPS_ROOT=%s", forCompose(cfg, cfg.AppsRoot)),
		fmt.Sprintf("DATA_ROOT=%s", forCompose(cfg, cfg.DataRoot)),
		fmt.Sprintf("NGINX_CONF_ROOT=%s", forCompose(cfg, cfg.NginxConfRoot)),
		fmt.Sprintf("NGINX_EXTERNAL_ROOT=%s", forCompose(cfg, cfg.NginxExternalRoot)),
		fmt.Sprintf("MYSQL_ROOT_PASSWORD=%s", cfg.MySQLRootPass),
		fmt.Sprintf("POSTGRES_SUPER_PASSWORD=%s", cfg.PostgresSuperPass),
		"",
	}, "\n")

	if err := os.MkdirAll(filepath.Dir(envPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(envPath, []byte(content), 0o644)
}
